name: React CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Cambia el número si tu proyecto usa otra versión

      - name: Instalar dependencias
        run: npm install

      - name: Construir proyecto
        run: npm run build
